name: datascience
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2023.5.7=hbcca054_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.2.0=h65d4601_19
  - libgomp=12.2.0=h65d4601_19
  - libnsl=2.0.0=h7f98852_0
  - libsqlite=3.42.0=h2797004_0
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libuuid=2.38.1=h0b41bf4_0
  - libzlib=1.2.13=h166bdaf_4
  - ncurses=6.3=h27087fc_1
  - openssl=3.1.0=hd590300_3
  - pcre2=10.40=hc3806b6_0
  - pip=23.1.2=pyhd8ed1ab_0
  - python=3.11.3=h2755cc3_0_cpython
  - readline=8.2=h8228510_1
  - setuptools=67.7.2=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - tzdata=2023c=h71feb2d_0
  - wheel=0.40.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - pip:
      - anyio==3.6.2
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.2.3
      - asttokens==2.2.1
      - async-lru==2.0.2
      - attrs==23.1.0
      - babel==2.12.1
      - backcall==0.2.0
      - beautifulsoup4==4.12.2
      - bleach==6.0.0
      - box2d-py==2.3.5
      - certifi==2023.5.7
      - cffi==1.15.1
      - charset-normalizer==3.1.0
      - cloudpickle==2.2.1
      - comm==0.1.3
      - contourpy==1.0.7
      - cycler==0.11.0
      - debugpy==1.6.7
      - decorator==5.1.1
      - defusedxml==0.7.1
      - executing==1.2.0
      - farama-notifications==0.0.4
      - fastjsonschema==2.17.1
      - fonttools==4.39.4
      - fqdn==1.5.1
      - gymnasium==0.28.1
      - idna==3.4
      - ipykernel==6.23.1
      - ipython==8.13.2
      - isoduration==20.11.0
      - jax-jumpy==1.0.0
      - jedi==0.18.2
      - jinja2==3.1.2
      - json5==0.9.14
      - jsonpointer==2.3
      - jsonschema==4.17.3
      - jupyter-client==8.2.0
      - jupyter-core==5.3.0
      - jupyter-events==0.6.3
      - jupyter-lsp==2.1.0
      - jupyter-server==2.5.0
      - jupyter-server-terminals==0.4.4
      - jupyterlab==4.0.0
      - jupyterlab-pygments==0.2.2
      - jupyterlab-server==2.22.1
      - kiwisolver==1.4.4
      - markupsafe==2.1.2
      - matplotlib==3.7.1
      - matplotlib-inline==0.1.6
      - mistune==2.0.5
      - nbclient==0.8.0
      - nbconvert==7.4.0
      - nbformat==5.8.0
      - nest-asyncio==1.5.6
      - notebook-shim==0.2.3
      - numpy==1.24.3
      - packaging==23.1
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==9.5.0
      - platformdirs==3.5.1
      - prometheus-client==0.17.0
      - prompt-toolkit==3.0.38
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pycparser==2.21
      - pygame==2.1.3
      - pygments==2.15.1
      - pyparsing==3.0.9
      - pyrsistent==0.19.3
      - python-dateutil==2.8.2
      - python-json-logger==2.0.7
      - pyyaml==6.0
      - pyzmq==25.0.2
      - requests==2.31.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - send2trash==1.8.2
      - six==1.16.0
      - sniffio==1.3.0
      - soupsieve==2.4.1
      - stack-data==0.6.2
      - swig==4.1.1
      - terminado==0.17.1
      - tinycss2==1.2.1
      - tornado==6.3.2
      - traitlets==5.9.0
      - typing-extensions==4.6.2
      - uri-template==1.2.0
      - urllib3==2.0.2
      - wcwidth==0.2.6
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.5.2
